### ISSUE TITLE
The token you supplied is invalid

### ISSUE THREAD

**Issue by pantasa** [ahmedayman4a/LyndaCoursesDownloader#13]
Hi, I got this error "The token you supplied is invalid". Not sure why is there an error since I still can watch those videos normally. 

However, my account is not a normal premium account but I have to log in through a company portal. Is this the reason for the error?

**Comment by ahmedayman4a** [comment]
Did you use the Extract Token button or did you extract the token cookie yourself from the browser?

**Comment by pantasa** [comment]
I've used both which produce the same result.

**Comment by ahmedayman4a** [comment]
> my account is not a normal premium account but I have to log in through a company portal.

This might be the reason for the error but I need to make sure first.
Do you log in from the same domain as lynda.com or is the login process from another domain?
Can you post a screenshot of lynda.com homepage while you are logged in?
