### ISSUE TITLE
Cant download this course - Finance for Non-Financial Managers?

### ISSUE THREAD

**Issue by swapnilprajapati1510** [ahmedayman4a/LyndaCoursesDownloader#15]
Do we need to login in in the lynda account?
Also it shows token is invalid

**Comment by ahmedayman4a** [comment]
Did you use the Extract Token button or did you extract the token yourself from the browser?

**Comment by pantasa** [comment]
I've used both which produce the same result.

**Comment by swapnilprajapati1510** [comment]
Hello Ahmed,

It shows me invalid token.

Also please let me know that should we login to our account in lynda for
downloading the videos?

Or it works without logging in?

**Comment by ahmedayman4a** [comment]
You need to login to download the videos
