### ISSUE TITLE
Lynda is Upgraded to LinkedIn and this software is not working anymore.

### ISSUE THREAD

**Issue by akmalelam** [ahmedayman4a/LyndaCoursesDownloader#16]
When I log in, it redirects me to LinkedIn and says **Your Lynda.com account has been upgraded, and your data will be moved to LinkedIn Learning**. I have a valid account and can still see the course on LinkedIn, but this software is no longer able to download any course.

**Comment by ahmedayman4a** [comment]
Linkedin learning is not supported by this tool. If I do acquire a linkedin learning account I might develop a downloader for it. They are completely different sites as they use different apis and have different layouts which means this downloader won't work on it.

**Comment by akmalelam** [comment]
Please develop one for that as well because Lynda is no longer working. Every time I log in, it redirects me to LinkedIn.

**Comment by AlexRomJJ** [comment]
Same problem from above

**Comment by pantasa** [comment]
Same problem

**Comment by mahdisky** [comment]
same problem , pls upgrade this app for linkedin

**Comment by ahmedayman4a** [comment]
I just got a linkedin learning account which means I might make a similar downloader for it

**Comment by AlexCodeLive** [comment]
Dear @ahmedayman4a, 
Please make it **LinkedIn Learning Compatibility**. Or Kindly make one like this for **LinkedIn Learning**. All major library has been upgraded to LinkedIn Learning and rest of on processing. You are a great contributor and we proud of you. A warm Thank You from my heart. Please make it, like you did make this like pro. Thank you again.

**Regards**
Alex

**Comment by ahmedayman4a** [comment]
I finished development of the extractor and the CLI for Linkedin Learning,
If anyone is up for beta testing it here is the download link : https://github.com/ahmedayman4a/Linkedin-Learning-Courses-Downloader/releases/tag/0.1
I will start working on the gui version and release it soon.
Tell me if you find any issues

**Comment by AlexCodeLive** [comment]
@ahmedayman4a , I can't find the (╠══What is the lynda security token?). Thank you
![image](https://user-images.githubusercontent.com/82458001/116186160-e49c5f00-a744-11eb-800e-b599154e50dd.png)

**Comment by ahmedayman4a** [comment]
I forgot to mention that the authentication token for linkedin learning is called `li_at`

**Comment by MohamedFaisal-BIM** [comment]
Oh man thank you soo much, this is working like a charm

**Comment by bestlong888** [comment]
The download exercise file is not working when there are two attachments like glossary

**Comment by ahmedayman4a** [comment]
This happens with the lynda app or the linkedin app?
And can you give me an example of a course with multiple exercise files?

**Comment by bestlong888** [comment]
https://www.lynda.com/Excel-tutorials/Excel-2019-Essential-Training/728368-2.html

It's lynda. I have yet tested it with linkedin, thanks for taking care of it.

**Comment by ahmedayman4a** [comment]
The lynda downloader doesn't have the functionality to download multiple exercise files but this feature is added to the linkedin learning downloader. I don't have a lynda account anymore so I can't add this feature to the lynda downloader

**Comment by bestlong888** [comment]
Thanks bro,I will test it with linkedin downloader.

**Comment by bestlong888** [comment]
Just tested your new linkedin downloader which is working fine. Look forward to seeing your gui one. thanks again.

**Comment by ahmedayman4a** [comment]
GUI version for LinkedIn Learning downloader is released. You can find it here : https://github.com/ahmedayman4a/Linkedin-Learning-Courses-Downloader
