### ISSUE TITLE
I'm getting this message please help

### ISSUE THREAD

**Issue by ankithrv** [ahmedayman4a/LyndaCoursesDownloader#17]
![lynda](https://user-images.githubusercontent.com/83707897/117318097-be469400-aea7-11eb-86be-bccea35de4d2.jpg)

**Comment by ahmedayman4a** [comment]
Go to `%localappdata%\LyndaCoursesDownloader\app-2.0.0\logs` and upload the most recent log files here

**Comment by ankithrv** [comment]
[log20210507.txt](https://github.com/ahmedayman4a/LyndaCoursesDownloader/files/6441885/log20210507.txt)

**Comment by ahmedayman4a** [comment]
For some reason the app can't connect to lynda.com. This could be caused by your firewall or antivirus. Try disabling them temporarily and see if it works.
Tell me if it doesn't work after turning off your firewall and antivirus

**Comment by ankithrv** [comment]
After blocking antivirus it worked. Thankssss!!!!!!!!

**Comment by ahmedayman4a** [comment]
Glad it worked
