### ISSUE TITLE
InvalidTokenException

### ISSUE THREAD

**Issue by Tana7y** [ahmedayman4a/LyndaCoursesDownloader#2]
I dont know what is going wrong keeps giving me this error

╠══[!!] An error occured : One or more errors occurred. (Exception of type 'LyndaCoursesDownloader.CourseExtractor.InvalidTokenException' was thrown.)
╠══[!!] Error details :    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at LyndaCoursesDownloader.ConsoleDownloader.Program.RunWithoutConfig()
#question

**Comment by ahmedayman4a** [comment]
Do you use firefox or chrome?

**Comment by Tana7y** [comment]
chrome

**Comment by ahmedayman4a** [comment]
Can you tell me the version of your chrome browser.
If you don't know how to get it follow this tutorial : https://help.zenplanner.com/hc/en-us/articles/204253654-How-to-Find-Your-Internet-Browser-Version-Number-Google-Chrome

**Comment by Tana7y** [comment]
Version 80.0.3987.149

**Comment by ahmedayman4a** [comment]
I have the same version which means the problem is probably on your side. We will figure something out. 
Could you copy the whole console with the error so that I can know exactly when this error happened?
You use windows ,right.

**Comment by ahmedayman4a** [comment]
I am sorry bare with me please.
I really recommend using firefox as it is much faster with my program.
Extraction speed test on my PC:
Extraction speed with firefox: 1~3 minutes 
Extraction speed with chrome: 3~6 minutes

**Comment by ahmedayman4a** [comment]
If there is no response for 48 hours I won't be able to fix the bug and will have to close thise issue. You can of course comment with more info even after closing the thread

**Comment by Tana7y** [comment]
i am sorry i wasn't here .. could u pls tell me what exactly u want me to do ?

**Comment by ahmedayman4a** [comment]
Don't worry.
I just need you to run the program again till you get the error and copy the whole program , everything written on the console from the start till the error and paste it here.

**Comment by ahmedayman4a** [comment]
Also, make sure you entered the right course url

**Comment by ahmedayman4a** [comment]
I will have to close this issue due to inactivity. If anyone has more info about this issue , please comment bellow and I will reopen it.
