### ISSUE TITLE
Unknown Error - "An error occurred while extracting the course. Try Again". 

### ISSUE THREAD

**Issue by sganpisetty** [ahmedayman4a/LyndaCoursesDownloader#5]
Getting extraction failed multiple times. 

"An error occurred while extracting the course. Try Again". 

Thanks for checking.
![error](https://user-images.githubusercontent.com/58684119/82841973-914adc80-9ef5-11ea-83bf-fca06f428dc6.JPG)

**Comment by ahmedayman4a** [comment]
Go to `%localappdata%\LyndaCoursesDownloader\app-1.0.0\logs` and upload the latest log.txt file

**Comment by edwardwong75** [comment]
I also have this error using Firefox, on some specific courses ( I didn't take note of which). Switching to Chrome (using slow method) it works for the same course that had the error on Firefox.

**Comment by ahmedayman4a** [comment]
@edwardwong75 If you encounter this error again, could you go to `%localappdata%\LyndaCoursesDownloader\app-1.0.0\logs` and upload the latest log.txt file here.

**Comment by edwardwong75** [comment]
[log20200717.txt](https://github.com/ahmedayman4a/LyndaCoursesDownloader/files/4935382/log20200717.txt)
I used Firefox to download some courses. I did not get an error prompt, but the last course just hung halfway through extraction (didn't move for more than 10 minutes). I closed the program and uploaded the log file for you. I noticed that Firefox always generates errors during extraction (but can successfully download the files after several retries). Chrome always works flawlessly (although you have to leave the Chrome window open to do the automated extraction).

**Comment by ahmedayman4a** [comment]
Thanks for the info.
I have a question. I think 4gb of ram or less causes errors especially with firefox but I want to make sure.
So, How many gigabytes of Ram do u have and what is the ram speed? You can find out in task manager > Performance > Memory

**Comment by edwardwong75** [comment]
> Thanks for the info.
> I have a question. I think 4gb of ram or less causes errors especially with firefox but I want to make sure.
> So, How many gigabytes of Ram do u have and what is the ram speed? You can find out in task manager > Performance > Memory

I have 16GB ram, DDR4 1300mhz (this is a Lenovo laptop).

**Comment by ahmedayman4a** [comment]
Then probably the ram is not the problem. I tested the app on a 4gb machine with 2 cores and I had an error nearly every time. Maybe the problem is with the number of cores in the processor. How many cores does your processor have?

**Comment by edwardwong75** [comment]
My CPU has 4 cores (8 threads).

**Comment by ahmedayman4a** [comment]
I am now working on a new extraction system that will dramatically decrease errors occurences
