### ISSUE TITLE
Batch downloading of multiple courses #enhancement

### ISSUE THREAD

**Issue by edwardwong75** [ahmedayman4a/LyndaCoursesDownloader#6]
Will you support batch downloading of multiple courses in a future release? In the Course URL field, the user can paste in the URLs of the courses they want to download, and the app will download each course into a sub-folder automatically. Usually the Token will not change in short period of time while all the courses are being downloaded.

Some other Lynda course downloaders can do this, but yours is the only one that works for me, so I'm hoping you can add this.

**Comment by ahmedayman4a** [comment]
Already mention on #3  that I will work on batch downloading of multiple courses. Thanks for the suggestion anyway.
